# Generated by Django 2.2.19 on 2022-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220509_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
